name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  RuboCop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - run: >
          bundle exec rubocop
          --fail-level F
          --display-only-fail-level-offenses
          --format clang
          --format github
          --parallel
          --color
  Test:
    name: Ruby ${{ matrix.ruby_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version:
          - '3.3'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Build gem
      run: |
        bundle exec rake build_and_report
    - run: |
        bundle exec rspec
  main:
    runs-on: ubuntu-latest
    needs:
      - Test
      - RuboCop
    steps:
      - run: |
         echo "Confirmed all jobs passed"
